version: '3'
services:
  php:
    container_name: browserquest_workman
    build: .
    image: browserquest_workman:dev
    privileged: false
    tty: true
    working_dir: /var/www/html
    ports:
      - 8000:8000
      - 8787:8787